from __future__ import annotations

import pytest

from himher.core.him import HIMVerifier, score
from himher.domains.handoff.counterpart import BernoulliHandModel
from himher.domains.handoff.env import Hand

CONTEXTS = (0, 1)


def _window_from(model: BernoulliHandModel, n_per_context: int = 25) -> list[tuple[int, Hand]]:
    """A deterministic window whose empirical frequencies exactly match
    model's theta (using round-number counts), so likelihood comparisons
    in tests are exact rather than depending on RNG draws.
    """
    window = []
    for context in CONTEXTS:
        theta = model.theta1 if context else model.theta0
        n_right = round(theta * n_per_context)
        window += [(context, Hand.R)] * n_right
        window += [(context, Hand.L)] * (n_per_context - n_right)
    return window


def test_score_is_the_windows_log_likelihood():
    model = BernoulliHandModel(0.5, 0.5)
    window = _window_from(model)
    from himher.core.model import history_log_likelihood

    assert score(model, window) == pytest.approx(history_log_likelihood(model, window))


def test_accepts_a_clearly_better_and_distinct_candidate():
    incumbent = BernoulliHandModel(0.1, 0.1)
    candidate = BernoulliHandModel(0.9, 0.9)
    window = _window_from(candidate)  # data generated by the candidate's own theta

    verifier = HIMVerifier(tau=0.0, delta=0.1, contexts=CONTEXTS)
    result = verifier.evaluate(candidate, incumbent, comparison_pool=(), window=window)

    assert result.accepted
    assert result.min_improvement > 0
    assert result.min_distinctness >= 0.1


def test_rejects_a_candidate_that_does_not_improve_on_the_incumbent():
    incumbent = BernoulliHandModel(0.9, 0.9)
    candidate = BernoulliHandModel(0.1, 0.1)
    window = _window_from(incumbent)  # data actually generated by the incumbent

    verifier = HIMVerifier(tau=0.0, delta=0.0, contexts=CONTEXTS)
    result = verifier.evaluate(candidate, incumbent, comparison_pool=(), window=window)

    assert not result.accepted
    assert result.min_improvement < 0


def test_rejects_a_candidate_too_close_to_an_existing_model():
    incumbent = BernoulliHandModel(0.1, 0.1)
    near_duplicate = BernoulliHandModel(0.1, 0.1)  # literally identical
    window = _window_from(near_duplicate)

    verifier = HIMVerifier(tau=-10.0, delta=0.05, contexts=CONTEXTS)
    result = verifier.evaluate(near_duplicate, incumbent, comparison_pool=(), window=window)

    # tau is permissive enough that improvement alone would pass; it is
    # distinctness that must reject this candidate.
    assert result.min_distinctness == pytest.approx(0.0)
    assert not result.accepted


def test_comparison_pool_participates_in_both_conditions():
    # Safe to compare against the full pool here because, by design
    # (HHCascade), the pool only ever contains previously-*selected*
    # models -- not every rejected attempt -- so it stays small and
    # meaningful rather than accumulating near-duplicates of the truth.
    incumbent = BernoulliHandModel(0.5, 0.5)
    library_model = BernoulliHandModel(0.6, 0.6)
    candidate = BernoulliHandModel(0.9, 0.9)
    window = _window_from(candidate)

    verifier = HIMVerifier(tau=0.0, delta=0.5, contexts=CONTEXTS)
    result = verifier.evaluate(
        candidate, incumbent, comparison_pool=(library_model,), window=window
    )

    # library_model (0.6) is closer to candidate (0.9) than incumbent
    # (0.5) is, so it should be the binding constraint on distinctness.
    from himher.core.model import model_divergence

    assert result.min_distinctness == pytest.approx(
        model_divergence(candidate, library_model, CONTEXTS)
    )


def test_a_reuse_candidate_drawn_from_the_library_can_still_be_accepted():
    # Regression test for the self-comparison edge case: if the candidate
    # were compared against itself (e.g. because the caller forgot to
    # exclude it from comparison_pool), ell(m') - ell(m') == 0 would never
    # exceed tau, and reuse could never be accepted. Callers must exclude
    # the candidate itself from comparison_pool.
    incumbent = BernoulliHandModel(0.1, 0.1)
    reuse_candidate = BernoulliHandModel(0.9, 0.9)
    other_library_model = BernoulliHandModel(0.5, 0.5)
    window = _window_from(reuse_candidate)

    verifier = HIMVerifier(tau=0.0, delta=0.0, contexts=CONTEXTS)
    result = verifier.evaluate(
        reuse_candidate,
        incumbent,
        comparison_pool=(other_library_model,),  # candidate itself excluded
        window=window,
    )
    assert result.accepted
